@userId = 01a02349-048f-7ab8-976c-b13ac39c72e1
@newPassword = test

### GET Users
GET {{BaseUrl}}/api/User
Content-Type: application/json
Accept: application/json
Authorization: {{jwt}}

> {% 
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    })
 %}

### Get User by Id
GET {{BaseUrl}}/api/User/{{userId}}
Content-Type: application/json
Accept: application/json
Authorization: {{jwt}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    })
%}

### Patch user
PATCH {{BaseUrl}}/api/User/{{userId}}
Content-Type: application/json
Accept: application/json
Authorization: {{jwt}}

[
  {
    "op": "replace",
    "path": "/passwordHash",
    "value": "test"
  }
]

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    })
%}

### Create User
POST {{BaseUrl}}/api/User
Content-Type: application/json
Accept: application/json
Authorization: {{jwt}}

{
  "userName": "SGC Trafy",
  "password": "fischerc",
  "memberSince": "2026-08-14",
  "discordId": "1025579600794894386",
  "role": 1
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    })
%}

### Delete User
DELETE {{BaseUrl}}/api/Player/{{userId}}
Content-Type: application/json
Accept: application/json
Authorization: {{jwt}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 204, "Response status is not 204");
    })
%}

### Set Password Recovery Code
PUT {{BaseUrl}}/api/User/set/recovery-code/{{userId}}
Content-Type: application/json
Accept: application/json
Authorization: {{jwt}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    })
%}

### Change Password
POST {{BaseUrl}}/api/User/password-change/request
Content-Type: application/json
Accept: application/json

{
  "newPassword": "test",
  "recoveryCode": "2135784240"
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200" 
            || response.status === 204, "Response status is not 204");
    })
%}